apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: test-service-vs
  namespace: apps-configuration
spec:
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
          - prefix: /
        routeAction:
          single:
            upstream:
              name: test-service-us
              namespace: apps-configuration